DBENGINE = None
APPPORT = 8888
APPHOST = '192.168.0.14'
APPNAME = 'FlaskTest'
APPSECRETKEY = 'A0Zr98j/3yX R~XHH!jmN]LWX/,?RT'
LOGINMANAGER = None
CONNECTIONSTRING = 'mysql+pymysql://root:maciek89@localhost/FlaskDB'